// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: nip_proxy/v1/service.proto

package nip_proxy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NipProxy_GetMetadata_FullMethodName = "/proto.hoppipolla.nip_proxy.v1.NipProxy/GetMetadata"
)

// NipProxyClient is the client API for NipProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NipProxyClient interface {
	GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*GetMetadataResponse, error)
}

type nipProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewNipProxyClient(cc grpc.ClientConnInterface) NipProxyClient {
	return &nipProxyClient{cc}
}

func (c *nipProxyClient) GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*GetMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetadataResponse)
	err := c.cc.Invoke(ctx, NipProxy_GetMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NipProxyServer is the server API for NipProxy service.
// All implementations must embed UnimplementedNipProxyServer
// for forward compatibility.
type NipProxyServer interface {
	GetMetadata(context.Context, *GetMetadataRequest) (*GetMetadataResponse, error)
	mustEmbedUnimplementedNipProxyServer()
}

// UnimplementedNipProxyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNipProxyServer struct{}

func (UnimplementedNipProxyServer) GetMetadata(context.Context, *GetMetadataRequest) (*GetMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetadata not implemented")
}
func (UnimplementedNipProxyServer) mustEmbedUnimplementedNipProxyServer() {}
func (UnimplementedNipProxyServer) testEmbeddedByValue()                  {}

// UnsafeNipProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NipProxyServer will
// result in compilation errors.
type UnsafeNipProxyServer interface {
	mustEmbedUnimplementedNipProxyServer()
}

func RegisterNipProxyServer(s grpc.ServiceRegistrar, srv NipProxyServer) {
	// If the following call pancis, it indicates UnimplementedNipProxyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NipProxy_ServiceDesc, srv)
}

func _NipProxy_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NipProxyServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NipProxy_GetMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NipProxyServer).GetMetadata(ctx, req.(*GetMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NipProxy_ServiceDesc is the grpc.ServiceDesc for NipProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NipProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.hoppipolla.nip_proxy.v1.NipProxy",
	HandlerType: (*NipProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetadata",
			Handler:    _NipProxy_GetMetadata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nip_proxy/v1/service.proto",
}
