# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import nip_pb2 as nip__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in nip_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class NipProxyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEnergyReadings = channel.unary_unary(
                '/hoppipolla.nip.NipProxy/GetEnergyReadings',
                request_serializer=nip__pb2.GetEnergyReadingsRequest.SerializeToString,
                response_deserializer=nip__pb2.GetEnergyReadingsResponse.FromString,
                _registered_method=True)
        self.GetGeoReadings = channel.unary_unary(
                '/hoppipolla.nip.NipProxy/GetGeoReadings',
                request_serializer=nip__pb2.GetGeoReadingsRequest.SerializeToString,
                response_deserializer=nip__pb2.GetGeoReadingsResponse.FromString,
                _registered_method=True)


class NipProxyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEnergyReadings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGeoReadings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NipProxyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEnergyReadings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnergyReadings,
                    request_deserializer=nip__pb2.GetEnergyReadingsRequest.FromString,
                    response_serializer=nip__pb2.GetEnergyReadingsResponse.SerializeToString,
            ),
            'GetGeoReadings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGeoReadings,
                    request_deserializer=nip__pb2.GetGeoReadingsRequest.FromString,
                    response_serializer=nip__pb2.GetGeoReadingsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hoppipolla.nip.NipProxy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hoppipolla.nip.NipProxy', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NipProxy(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEnergyReadings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hoppipolla.nip.NipProxy/GetEnergyReadings',
            nip__pb2.GetEnergyReadingsRequest.SerializeToString,
            nip__pb2.GetEnergyReadingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGeoReadings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hoppipolla.nip.NipProxy/GetGeoReadings',
            nip__pb2.GetGeoReadingsRequest.SerializeToString,
            nip__pb2.GetGeoReadingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
