# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: path.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npath.proto\x12\x0fhoppipolla.path\x1a\x1fgoogle/protobuf/timestamp.proto\"#\n\x03Hop\x12\x0e\n\x06isd_as\x18\x01 \x01(\t\x12\x0c\n\x04ifid\x18\x02 \x01(\t\"\xb6\x01\n\x04Path\x12\x13\n\x0b\x66ingerprint\x18\x01 \x01(\t\x12\x12\n\nsrc_isd_as\x18\x02 \x01(\t\x12\x12\n\ndst_isd_as\x18\x03 \x01(\t\x12\x10\n\x08sequence\x18\x04 \x01(\t\x12.\n\nexpiration\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0b\n\x03mtu\x18\x06 \x01(\x04\x12\"\n\x04hops\x18\x07 \x03(\x0b\x32\x14.hoppipolla.path.Hop\"-\n\x16GetPathsForAddrRequest\x12\x13\n\x0b\x64\x65stination\x18\x01 \x01(\t\"?\n\x17GetPathsForAddrResponse\x12$\n\x05paths\x18\x01 \x03(\x0b\x32\x15.hoppipolla.path.Path2v\n\x0cPathAnalyzer\x12\x66\n\x0fGetPathsForAddr\x12\'.hoppipolla.path.GetPathsForAddrRequest\x1a(.hoppipolla.path.GetPathsForAddrResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'path_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HOP']._serialized_start=64
  _globals['_HOP']._serialized_end=99
  _globals['_PATH']._serialized_start=102
  _globals['_PATH']._serialized_end=284
  _globals['_GETPATHSFORADDRREQUEST']._serialized_start=286
  _globals['_GETPATHSFORADDRREQUEST']._serialized_end=331
  _globals['_GETPATHSFORADDRRESPONSE']._serialized_start=333
  _globals['_GETPATHSFORADDRRESPONSE']._serialized_end=396
  _globals['_PATHANALYZER']._serialized_start=398
  _globals['_PATHANALYZER']._serialized_end=516
# @@protoc_insertion_point(module_scope)
