# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: path.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npath.proto\x12\x0fhoppipolla.path\"L\n\x03Hop\x12\x0e\n\x06isd_as\x18\x01 \x01(\t\x12\x19\n\x11inbound_interface\x18\x02 \x01(\r\x12\x1a\n\x12outbound_interface\x18\x03 \x01(\r\"\x9a\x01\n\x04Path\x12\x13\n\x0b\x66ingerprint\x18\x01 \x01(\t\x12\x12\n\nsrc_isd_as\x18\x02 \x01(\t\x12\x12\n\ndst_isd_as\x18\x03 \x01(\t\x12\x10\n\x08sequence\x18\x04 \x01(\t\x12\x12\n\nexpiration\x18\x05 \x01(\t\x12\x0b\n\x03mtu\x18\x06 \x01(\x04\x12\"\n\x04hops\x18\x07 \x03(\x0b\x32\x14.hoppipolla.path.Hop\",\n\x15GetPathForAddrRequest\x12\x13\n\x0b\x64\x65stination\x18\x01 \x01(\t\"K\n\x16GetPathForAddrResponse\x12(\n\x04path\x18\x01 \x01(\x0b\x32\x15.hoppipolla.path.PathH\x00\x88\x01\x01\x42\x07\n\x05_path2s\n\x0cPathAnalyzer\x12\x63\n\x0eGetPathForAddr\x12&.hoppipolla.path.GetPathForAddrRequest\x1a\'.hoppipolla.path.GetPathForAddrResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'path_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HOP']._serialized_start=31
  _globals['_HOP']._serialized_end=107
  _globals['_PATH']._serialized_start=110
  _globals['_PATH']._serialized_end=264
  _globals['_GETPATHFORADDRREQUEST']._serialized_start=266
  _globals['_GETPATHFORADDRREQUEST']._serialized_end=310
  _globals['_GETPATHFORADDRRESPONSE']._serialized_start=312
  _globals['_GETPATHFORADDRRESPONSE']._serialized_end=387
  _globals['_PATHANALYZER']._serialized_start=389
  _globals['_PATHANALYZER']._serialized_end=504
# @@protoc_insertion_point(module_scope)
