name: CI

on:
  push:
    branches:
      - main
      - workflows # for testing
  pull_request:
    branches:
      - main

jobs:
  nip-proxy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./services/nip-proxy

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: nip-proxy

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build @hoppipolla/nip-proxy
        run: docker build . -t eu.gcr.io/hoppipolla/nip-proxy:${{ github.sha }}

  path-analyzer:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./services/path-analyzer

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: path-analyzer

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build @hoppipolla/path-analyzer
        run: docker build . -t eu.gcr.io/hoppipolla/path-analyzer:${{ github.sha }}
